### ISSUE TITLE
Authenticated routes?

### ISSUE THREAD

**Issue by badsyntax** [abhinaba-ghosh/playwright-lighthouse#14]
Hi. I've attempting to use this library to run lighthouse on authenticated routes, but i'm having some difficulty. I see you're setting disableStorageReset:

https://github.com/abhinaba-ghosh/playwright-lighthouse/blob/88699bff7ad9038a5c9c38d69e79454b60bb53a3/src/task.js#L57

This is good, but the problem is auth state is not shared between browser contexts.

I understand the problem as:

1. Playwright launches chrome
2. Playwright creates a new isolated browser context (incognito)
3. Playwright injects the auth state into this browser window
4. Lighthouse opens an entirely new window (and browser context) from the chrome instance
5. Auth state is not carried across to the lighthouse window

Did you ever get this to work? Can you offer any advice?

**Comment by badsyntax** [comment]
This appears to only work when using `launchPersistentContext`:


```js
const userDataDir = '/path/to/data/dir';

const browser = await chromium.launchPersistentContext(userDataDir, {
  args: ['--remote-debugging-port=9222'],
});
const page = await browser.newPage();
await page.goto('http://localhost:3000/');

// Perform your login steps here which will save to cookie or localstorage

// When lighthouse opens a new page the storage will be pesisted meaning the new page will have the same session (either via cookie or localstorage)
await playAudit({
  page: page,
  port: 9222,
});
```

Unfortunately I can't figure out how to use `launchPersistentContext` with the Playwright Test Runner.

**Comment by abhinaba-ghosh** [comment]
Thanks @badsyntax

**Comment by badsyntax** [comment]
I've figured out how to do this here: https://github.com/microsoft/playwright/issues/7447#issuecomment-879803423

But I want to wait for some feedback from the playwright authors before adding that info to the README in this repo.

**Comment by abhinaba-ghosh** [comment]
You can add the info to the readme and change it later if needed. 😇
