### ISSUE TITLE
Change View Port settings like Width and Height

### ISSUE THREAD

**Issue by ganeshsirsi** [abhinaba-ghosh/playwright-lighthouse#17]
I am not able to change view port settings like width and height of my screen
is there any options?

**Comment by manuman94** [comment]
Hi @ganeshsirsi!

I don't think you can control viewport size settings in pixels. I believe you can only choose the form factor as described in node_modules/lighthouse/lighthouse-core/config/lr-desktop.config.js and lr-mobile-config.js

Form factor can only be set to 'desktop' or 'mobile'.

I don't find the setting to change this.

**Comment by grybykm** [comment]
@ganeshsirsi you may set the viewport in playwright itself `viewport: { width: 1920, height: 1080 },` and disable emulation in the lighthouse `{ opts: { screenEmulation: { disabled: true } } }`

**Comment by manuman94** [comment]
I think that changing Playwright browser size does not affect the Lighthouse report, as it has its own mobile/desktop sizes. Is it possible?

**Comment by grybykm** [comment]
With `screenEmulation` disabled lighthouse doesn't change browser window sizes during the test so I expect it uses only the current viewport
