### ISSUE TITLE
Lighthouse fails because of old version

### ISSUE THREAD

**Issue by angelovdev** [abhinaba-ghosh/playwright-lighthouse#22]
This package depends on version 8.6.0 of lighthouse and fails when I try to run it with 8.6.0 installed.

```
Error: connect ECONNREFUSED ::1:9222

        at TCPConnectWrap.afterConnect [as oncomplete]
```

If I install the latest version 9.2.0 it succeeds locally where I use yarn but fails when being deployed to the cloud because of npm's peerDependancy installation.

Can you update the dependency to the latest version of lighthouse?

**Comment by abhinaba-ghosh** [comment]
This is available in `v2.1.1` 🎉
