### ISSUE TITLE
An option to pass url instead of page

### ISSUE THREAD

**Issue by grybykm** [abhinaba-ghosh/playwright-lighthouse#24]
**Concern** 

Opening a page one extra time more and keeping it opened consumes 2 times more resources. It's especially noticeable when running tests in parallel.

There is no real need to pass `page` to `playAudit`. It's used to perform some validations and get the url.

**Solution**

An option to pass url string instead of page.

ex: if page is string use it as url and skip all the checks.

I can raise the PR if you are ok with this.

Thank you

**Comment by abhinaba-ghosh** [comment]
Hi @grybykm this makes a lot of sense. 

Kindly raise a PR. This will be a breaking change though

**Comment by grybykm** [comment]
It should not be a breaking change I believe unless we want to drop `page` support completely

**Comment by abhinaba-ghosh** [comment]
@grybykm looks great. Let's do this.
