### ISSUE TITLE
Why do we get two windows? 

### ISSUE THREAD

**Issue by basalona** [abhinaba-ghosh/playwright-lighthouse#29]
When I run the tests I am getting two browser windows open, one with normal resolutions and another one with mobile? Is this an expected behavior?

**Comment by alexOliveira87** [comment]
Yes, lighthouse has checks also for mobile.
if you want to disable the mobile checks you can add this to your `playAudit`:
`opts: { screenEmulation: false },`

**Comment by fasatrix** [comment]
@alexOliveira87 I get the following error if I try

![image](https://user-images.githubusercontent.com/16127426/180893012-d848d619-0963-4b7e-bed0-83924d6676e0.png)

**Comment by fasatrix** [comment]
I think the actual entry is this:  `opts: { screenEmulation: { disabled: true } }`
