### ISSUE TITLE
Issue with port

### ISSUE THREAD

**Issue by moksh-tehlan** [abhinaba-ghosh/playwright-lighthouse#33]
Test case is throwing an error `Error: connect ECONNREFUSED 127.0.0.1:9222
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)`

Test Case
`  test('lighthouse audit report', async ({browser}) => {
    // same browser instance being shared between all test cases
    // then creating a page
    page = await browser.newPage();

    // instance of LoginPage
    loginPage = new LoginPage(page);

    // instance of BrowserSession
    browserSession = new BrowserSession(page);

    // page.goto() is being implemented in .startTest();
    await browserSession.startTest(loginData.url,page);

    // The page lands on a signIn Page .signIn() is used to signIn on that page using credentials
    await loginPage.signIn(scopeData.workspace_editor.username, scopeData.workspace_editor.password);
    
    // playAudit is a playwright-lighthouse function used to do lighthouse testing
    await playAudit({
        page: page,
        thresholds: {
          performance: 0,
          accessibility: 0,
          'best-practices': 0,
          seo: 0,
          pwa: 0,
        },
        port: 9222,
        reports: {
          formats: {
            json: false,
            html: true,
            csv: false,
          },
          name: "lighthouse-report",
          directory: `${process.cwd()}/test-results/lighthouse-test`,
        }
    });
    await browser.close()
}); `
Playwright config file

` use: {
    headless: false,
    args: ['--remote-debugging-port=9222'],
    viewport: { width: 1920, height: 1080 },
    ignoreHTTPSErrors: true,
    trace: 'retain-on-failure',
    // Each action is given 60 seconds
    actionTimeout: 60000,
    browserName: 'chromium',
    screenshot: 'only-on-failure',
  } `

**Comment by moksh-tehlan** [comment]
found the bug

**Comment by SusantoMandal** [comment]
I'm having the same problem with port. Can you explain how to resolve it?
