### ISSUE TITLE
not opening the state where I left

### ISSUE THREAD

**Issue by moksh-tehlan** [abhinaba-ghosh/playwright-lighthouse#34]
Hi Everyone,
Actually what's happening is I'm trying to test a website 
where I first put my id and password on first page 
the when I try to test it using the playAudit it goes back to the login page and start testing over there not on the home page
what can I do

**Comment by badsyntax** [comment]
If you need to persist state then you need to use a persistent context, see: https://github.com/abhinaba-ghosh/playwright-lighthouse#running-lighthouse-on-authenticated-routes

**Comment by moksh-tehlan** [comment]
it's not working it still can't login

**Comment by moksh-tehlan** [comment]
It's working there was just a little code problem from my side

**Comment by CkumarGitHub** [comment]
> It's working there was just a little code problem from my side

Could you please share the code problem ?
It is not working for me
