### ISSUE TITLE
Anyway to use flow = await lighthouse.startFlow(page) for a playwright page?

### ISSUE THREAD

**Issue by xbhoneybee** [abhinaba-ghosh/playwright-lighthouse#38]
I use playwright to do E2E test, but I also want to use lighthouse flow to get a report of flow. Do you have any idea for that?

BTW how do you use playwright to do a performance test?

**Comment by toukolonka** [comment]
Did you manage to get this work?

**Comment by xbhoneybee** [comment]
> Did you manage to get this work?
@toukolonka 
No, I think it is impossible for the playwright page object compatible with lighthouse puppeteer page object.

BTW I get another solution for playwright performance test. Datadog has support playwright in the CI Test now.
