### ISSUE TITLE
getting error for module

### ISSUE THREAD

**Issue by vbpatel73** [abhinaba-ghosh/playwright-lighthouse#45]
I am getting this error:

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\projects\playwright_lighthouse_report\node_modules\lighthouse\core\index.js from C:\projects\playwright_lighthouse_report\node_modules\playwright-lighthouse\src\task.js not supported.
Instead change the require of index.js in C:\projects\playwright_lighthouse_report\node_modules\playwright-lighthouse\src\task.js to a dynamic import() which is available in all CommonJS modules.

how to solve it pls?

**Comment by jaktestowac** [comment]
https://stackoverflow.com/a/75488863/1266040 here you are :D
