### ISSUE TITLE
Types issue: playwright-core

### ISSUE THREAD

**Issue by mikeybinns** [abhinaba-ghosh/playwright-lighthouse#65]
I'm getting a type error because the `Page` type imported in index.d.ts doesn't match the `Page` type from the newest versions of playwright-core.

I believe this can be resolved by updating the dependency to be more lenient by adding the `^` symbol, so it would be `"playwright-core": "^1.19.2",` as this would allow you to keep the types in line with the latest non-breaking version.

I also think you should possibly update the `playwright-core` package dependency from a dev dependency to an optional peer dependency, however, I am not sure how this could affect other package installs. This would make logical sense as the package isn't only used for developing the package if the types are exported like you have done.

Should this be acceptable, I'm happy to submit a PR implementing these fixes.

**Comment by abhinaba-ghosh** [comment]
kindly raise a PR

**Comment by abhinaba-ghosh** [comment]
This is now available in `v3.2.2`
