### ISSUE TITLE
Regression: comparisonError is missing in playAudit return type

### ISSUE THREAD

**Issue by mgrybyk** [abhinaba-ghosh/playwright-lighthouse#67]
Since one of the last types related  commits there is a regression. 

`comparisonError` is missing.

<img width="477" alt="image" src="https://github.com/abhinaba-ghosh/playwright-lighthouse/assets/25589559/7fc9054b-8f96-42ca-b3ce-339b0f024f6a">

**Comment by mgrybyk** [comment]
Will be fixed with https://github.com/abhinaba-ghosh/playwright-lighthouse/pull/68

**Comment by abhinaba-ghosh** [comment]
The fix is available in `v 3.2.6`
